language: php

php:
 - '7.0'

cache:
  directories:
   - node_modules
   - vendor

before_install:
 - nvm install 6.5.0
 - nvm use 6.5.0

install:
 - npm install
 - composer install

script:
 - npm run lint
 - npm run compile

after_success:
 # If the build was triggered by a tag, publish the new version
 - 'if [[ $TRAVIS_TAG == v* ]]; then vsce publish -p $VSCE_TOKEN; fi'
